// Generated by CoffeeScript 1.3.1
(function() {

  define(["backbone", "marionette"], function(Backbone, Marionette) {
    this.App = new Backbone.Marionette.Application();
    this.App.addRegions({
      mainRegion: "#main"
    });
    this.App.on("initialize:after", function() {
      if (!Backbone.history.started) {
        return Backbone.history.start();
      }
    });
    return this.App;
  });

}).call(this);
