// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  define(["../../../app", "tpl!../../../../sources/pages/default.tpl"], function(App, Template) {
    return App.module("Page.Views", function(Views, App, Backbone, Marionette, $, _) {
      return Views.Show = (function(_super) {

        __extends(Show, _super);

        Show.name = 'Show';

        function Show() {
          return Show.__super__.constructor.apply(this, arguments);
        }

        Show.prototype.template = Template;

        Show.prototype.className = 'page';

        Show.prototype.initialize = function() {
          var page_id,
            _this = this;
          page_id = this.model.get('id');
          return _.defer(function() {
            return require(['tpl!../sources/pages/' + page_id + '.tpl'], function(tpl) {
              _this.template = tpl;
              return _this.render();
            });
          });
        };

        return Show;

      })(Marionette.ItemView);
    });
  });

}).call(this);
